
/* TABLO OLUSTURMA */
CREATE TABLE CALISMA(
TC INT NOT NULL,
AD VARCHAR(30),
SOYAD VARCHAR(30),
yas INT,
CINSIYET CHAR(1),
CONSTRAINT PK_CALISMA PRIMARY KEY (TC)
);

/* TABLOYA VERÝ EKLEME */
INSERT INTO CALISMA
VALUES
(100,'ALI','VELI',25,'E'),
(101,'AHMET','MEHMET',35,'K');

/* SONRADAN PRIMARY KEY EKLEME */
ALTER TABLE CALISMA
ADD CONSTRAINT PK_CALISMA PRIMARY KEY (TC);


/* VAR OLAN TABLOYA SÜTUN EKLEME */
ALTER TABLE CALISMA
ADD SEHIR VARCHAR(20);

/* VAR OLAN TABLOYA SÜTUN EKLEME */
ALTER TABLE CALISMA
ADD Email varchar(255);

/* VAR OLAN TABLODAN SÜTUN SÝLME */
ALTER TABLE CALISMA
DROP COLUMN Email;

/* VAR OLAN TABLONUN VAR OLAN SÜTUNUNDA DÜZENLEME YAPMA */
ALTER TABLE CALISMA
ALTER COLUMN SEHIR VARCHAR(30);

/* UNIQUE KULLANIMI ORNEK */
ALTER TABLE CALISMA
ADD OGRENCINO INT NOT NULL; /* DILENIRSE ILK EKLENDIGINDE SONUNA UNIQUE YAZILARAK CONSTRAINTSIZ SEKILDE EKLENEBÝLÝR */

ALTER TABLE CALISMA /* ISTENIRSE SONRADAN CONSTRAINT KULLANMADAN BU SEKÝLDE EKLENEBÝLÝR */
ADD UNIQUE (OGRENCINO); 

ALTER TABLE CALISMA /* ISTENIRSE SONRADAN CONSTRAINT KULLANARAK BU SEKÝLDE EKLENEBÝLÝR */
ADD CONSTRAINT UC_OgrenciNo UNIQUE (OGRENCINO);

/* PRIMARY KEY ÝPTALÝ */
ALTER TABLE OGRENCI
DROP CONSTRAINT PK_CALISMA;

/* FOREIGN KEY KULLANIMI VE PRIMARY KEY BAGLANTISI */

CREATE TABLE CALISMA2(
	TC INT PRIMARY KEY,
	BOY INT,
	KILO INT,
	CONSTRAINT FK_CALISMA2 FOREIGN KEY (TC) REFERENCES CALISMA(TC)
);


/* SELECT KULLANIMI */

SELECT * FROM CALISMA;

SELECT * FROM CALISMA2;

SELECT * FROM CALISMA 
WHERE TC = ' 100 ';

SELECT * FROM CALISMA
WHERE CINSIYET = 'E';

SELECT * FROM CALISMA
WHERE TC < 100;


/* UPDATE KULLANIMI */

ALTER TABLE CALISMA   /* ÖNCE TABLOMUZA MAAS DÝYE BÝR COLUMN EKLEYELÝM */
ADD MAAS INT

INSERT INTO CALISMA
VALUES
(102,'ALI','VELI',25,'E',5000),
(103,'AHMET','MEHMET',35,'K',6000),  /* TABLOMUZA YENÝ DATALAR GÝRELÝM */
(104,'ALI','VELI',25,'E',7000),
(105,'AHMET','MEHMET',35,'K',8000);

SELECT * FROM CALISMA WHERE MAAS IS NULL; /* MAAS DEÐERÝ NULL OLANLARI GETÝR */

UPDATE CALISMA
SET MAAS = 5000   /* MAASI NULL OLANLARIN HEPSINI 5000 MAAS YAPTIK */
WHERE MAAS IS NULL; 

UPDATE CALISMA
SET MAAS = MAAS * 1.2  /* HERKESE %20 ZAM YAPTIK */

UPDATE CALISMA
SET MAAS = MAAS * 1.1 /* ERKEKLERE %10 DAHA ZAM YAPTIK */
WHERE CINSIYET = 'E';

SELECT * FROM CALISMA


/* LIKE KULLANIMI */
SELECT * FROM CALISMA WHERE SOYAD LIKE 'V%';	 /* V ÝLE BASLAYAN */
SELECT * FROM CALISMA WHERE SOYAD LIKE '%T';	/* T ÝLE BÝTEN */
SELECT * FROM CALISMA WHERE SOYAD LIKE '%EH%';	/* ÝÇÝNDE EH GEÇEN */

/* LEFT JOIN KULLANIMI */

INSERT INTO CALISMA2
VALUES
(1,100,40),
(2,120,50),
(100,140,60),
(101,90,60),   /* IKINCI TABLOMUZA VERÝ EKLEYELÝM */
(102,85,50),
(103,100,70),
(104,150,75),
(105,95,55);


SELECT A.AD,A.SOYAD, B.TC , B.KILO , B.BOY
FROM CALISMA A
LEFT JOIN CALISMA2 B ON A.TC = B.TC

SELECT A.AD,A.SOYAD, B.TC , B.KILO , B.BOY
FROM CALISMA A
LEFT JOIN CALISMA2 B ON A.TC = B.TC
WHERE B.BOY>100

/* INDEX OLUSTURMA */
CREATE INDEX indexTC ON CALISMA(TC);

/* FONKSIYONLAR
COUNT(): Bir gruptaki satýr sayýsýný veya NULL olmayan deðerlerin sayýsýný döndürür.
SUM(): Bir sayýsal sütundaki deðerlerin toplamýný döndürür.
AVG(): Bir sayýsal sütundaki deðerlerin ortalamasýný döndürür.
MIN(): Bir sütundaki en küçük deðeri döndürür.
MAX(): Bir sütundaki en büyük deðeri döndürür.
*/
